allow-missing-formatter = false
on-unmatched = "fatal"
verbose = 0
excludes = [
  # keep-sorted start
  "flake.lock",
  # The way the nix builds work is that a derivation is by vendoring the go
  # dependencies. This means that in the lint check ran via `nix flake check` the
  # vendor directory would be present and be processed by `treefmt` which is
  # unnecessary.
  "vendor/*",
  # keep-sorted end
]

[formatter.all-typos]
command = "typos"
options = ["--write-changes"]
includes = ["*"]
priority = -2

[formatter.all-keep-sorted]
command = "keep-sorted"
includes = ["*"]
priority = -1

[formatter.go-fmt]
command = "pastyears"
options = ["lint", "go"]
includes = ["*.go"]

[formatter.md-fmt]
command = "mdformat"
options = ["--number", "--wrap", "80"]
includes = ["*.md"]

[formatter.nix-fmt]
command = "nixfmt"
options = ["--verify"]
includes = ["*.nix"]

[formatter.toml-fmt]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
