allow-missing-formatter = false
on-unmatched = "fatal"
verbose = 0
excludes = [
  # keep-sorted start
  "flake.lock",
  "go.mod",
  "go.sum",
  # keep-sorted end
]

[formatter.all-typos]
command = "typos"
options = ["--write-changes"]
includes = ["*"]
priority = -2

[formatter.all-keep-sorted]
command = "keep-sorted"
includes = ["*"]
priority = -1

[formatter.go-fmt]
# `golangci-lint` does not play well with linting/formatting only specific files so
# just run it over the entire project whenever a go file changes.
command = "bash"
options = ["-euo", "pipefail", "-c", "golangci-lint run --fix ./..."]
includes = ["*.go"]

[formatter.md-fmt]
command = "mdformat"
options = ["--number", "--wrap", "80"]
includes = ["*.md"]

[formatter.nix-fmt]
command = "nixfmt"
options = ["--verify"]
includes = ["*.nix"]

[formatter.toml-fmt]
command = "taplo"
options = ["format"]
includes = ["*.toml"]

[formatter.yaml-fmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
