#!/bin/sh

set -eu

echo "info: running pre-commit hooks"

if [ ! -v "IN_NIX_SHELL" ]; then
  system="x86_64-linux"

  # No need for `--include-untracked` here since `nix build` will not copy
  # over untracked files.
  git stash --quiet --keep-index
  nix build \
    --no-link \
    --no-update-lock-file \
    ".#checks.$system.lint" || (git stash pop --quiet && exit 1)
  git stash pop --quiet
  
  exit 0
fi

go run ./cmd/pastyears pre-commit
