---
on:
  issue_comment:
    types: [created]

jobs:
  approve-pr:
    name: "Approve PR"
    runs-on: ubuntu-24.04
    if: ${{ github.event.issue.pull_request && github.event.comment.author_association == "OWNER" }}
    env:
      PR_COMMENT: "${{ github.event.comment.body }}"
      PR_NUMBER: "${{ github.event.issue.number }}"
      FULL_EVENT: "${{ toJson(github.event) }}"
    steps:
      - name: "Check if comment is approval comment."
        run: |-
          set -eu

          if [ -z "$PR_COMMENT" ]; then
            echo "info: PR_COMMENT is empty; skipping"

            exit 0
          fi

          allowed_comments=("LGTM" "LGTM." "Approve" "Approve.")
          for comment in "${allowed_comments[@]}"
          do
            if [ "$comment" == "$PR_COMMENT" ]; then
              echo "info: found approval comment: $PR_COMMENT"
              gh pr review "$PR_NUMBER" --approve

              exit 0
            fi
          done

          echo "info: no matching approvaal comment was found"
