---
on:
  issue_comment:
    types: [created]

jobs:
  approve-pr:
    name: "Approve PR"
    runs-on: ubuntu-24.04
    if: ${{ github.event.issue.pull_request && github.event.comment.author_association == 'OWNER' && github.event.comment.body == 'LGTM' }}
    env:
      PR_NUMBER: "${{ github.event.issue.number }}"
      GH_TOKEN: "${{ github.token }}"
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - run: gh pr review "$PR_NUMBER" --approve
