---
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          logger: pretty
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build ".#checks.$(nix eval --impure --raw --expr 'builtins.currentSystem').lint"
