on:
  push:
    branches:
      - main
  pull_request_target:

permissions: read-all

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5      
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          gc-max-store-size: 2G
          # Purge the caches that were last accessed 2 days ago.
          purge-last-accessed: 172800
      - name: Run checks
        run: nix flake check
